# Generated by Django 5.2.1 on 2025-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_type', models.CharField(help_text='e.g., Sedan, SUV, Truck, Van', max_length=50)),
                ('features', models.TextField(blank=True, help_text='List features like GPS, sunroof, etc.', null=True)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
            ],
        ),
    ]
